// <auto-generated />
/*
 * FILE ROLE: Model snapshot - frozen picture of the entire model after the latest migration.
 *
 * SECTIONS IN THIS FILE:
 *   8. StoreDbContextModelSnapshot
 *
 * SECTION 8: MODEL SNAPSHOT
 *
 * StoreDbContextModelSnapshot.cs is updated every time you add a migration.
 * EF compares your current entity classes + DbContext to this snapshot to
 * compute the next migration diff.
 *
 * Key annotations:
 *   ProductVersion     EF Core version that generated the snapshot (8.0.11 here)
 *   BuildModel(...)    Fluent-style description of every entity, property, key, FK
 *
 * The snapshot is not applied to the database directly - it is metadata for the
 * tooling. The database schema comes from running Up() in migration classes.
 * -------------------------------------------------------------------------
 */
using CodeFirstModelsAndMigrations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstModelsAndMigrations.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstModelsAndMigrations.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CodeFirstModelsAndMigrations.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CodeFirstModelsAndMigrations.Models.Product", b =>
                {
                    b.HasOne("CodeFirstModelsAndMigrations.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CodeFirstModelsAndMigrations.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
