/*
 * TOPIC: Client-Side Validation in ASP.NET Core MVC
 *
 * WHY IT MATTERS:
 *   Server-side validation (DataAnnotations + ModelState) is authoritative but requires
 *   a round-trip. Client-side validation gives immediate feedback WITHOUT a page reload,
 *   improving UX and reducing unnecessary server load. In ASP.NET Core MVC the two tiers
 *   are linked automatically: the same DataAnnotations that drive server validation also
 *   emit HTML data-val-* attributes that the jQuery Unobtrusive Validation library reads
 *   at runtime — so you write the rule once and get both tiers for free.
 *
 * WHAT YOU WILL LEARN:
 *   1. How unobtrusive validation works (jquery.validate + jquery.validate.unobtrusive
 *      + data-val-* attributes generated by Tag Helpers / Html Helpers)
 *   2. Which DataAnnotations produce which data-val-* attributes (Required, StringLength,
 *      Range, RegularExpression, Compare, EmailAddress)
 *   3. How to implement IClientModelValidator on a custom attribute so it emits its own
 *      data-val-* attributes alongside server-side logic
 *   4. How to register a matching custom jQuery validator method and unobtrusive adapter
 *   5. How asp-validation-for / asp-validation-summary Tag Helpers render data-valmsg-*
 *   6. Three ways to include the required scripts: CDN, LibMan, bundling
 *   7. How to re-validate after dynamic DOM changes with $.validator.unobtrusive.parse()
 *
 * CHAPTER MAP:
 *   1. How unobtrusive validation works         → Program.cs  (this file — Section 1)
 *   2. DataAnnotations → data-val-* attributes  → Models/RegistrationViewModel.cs
 *   3. Custom attribute model                   → Models/EventViewModel.cs
 *   4. IClientModelValidator implementation     → Validation/FutureDateAttribute.cs
 *   5. Controller: GET/POST + server fallback   → Controllers/AccountController.cs
 *   6. Validation tag helpers in views          → Views/Account/Register.cshtml
 *   7. Required scripts: CDN / LibMan / bundle  → Views/Shared/_ValidationScriptsPartial.cshtml
 *   8. Custom client adapter registration       → Views/Shared/_ValidationScriptsPartial.cshtml
 *   9. Re-validating after dynamic DOM changes  → Views/Shared/_ValidationScriptsPartial.cshtml
 */

using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

/*
 * SECTION 1: HOW UNOBTRUSIVE VALIDATION WORKS
 *
 * Pipeline summary:
 *
 *   [DataAnnotation on model property]
 *         │
 *         ▼  (Tag Helper / HtmlHelper renders the <input>)
 *   data-val="true"  data-val-required="The field is required."
 *         │
 *         ▼  (jquery.validate.unobtrusive scans the DOM at document-ready)
 *   $.validator.unobtrusive.parse(form)   ← reads data-val-* attrs, calls
 *         │                                  $.validator.addRule() internally
 *         ▼
 *   jquery.validate.js validates the field on blur / keyup / submit
 *         │
 *         ▼  (unobtrusive writes the error into the matching span)
 *   <span data-valmsg-for="FieldName">The field is required.</span>
 *
 * Key components:
 *   jquery.js                      — base DOM / event library
 *   jquery.validate.js             — core validation engine (rules, messages, methods)
 *   jquery.validate.unobtrusive.js — bridge: reads data-val-* attrs → calls validate API
 *
 * Load ORDER matters — each script depends on the one above it in the list.
 * jQuery must be in the layout; the other two go in _ValidationScriptsPartial (per-page).
 *
 * Server fallback:
 *   Client-side validation can be bypassed (JS disabled, Postman, curl).
 *   Always check ModelState.IsValid in POST actions — Section 5 covers this.
 *
 * Data attributes on a rendered <input>:
 *   data-val="true"                  ← triggers unobtrusive parsing for this element
 *   data-val-required="..."          ← [Required]
 *   data-val-length="..."            ← [StringLength]
 *   data-val-length-max="50"
 *   data-val-length-min="3"
 *   data-val-range="..."             ← [Range]
 *   data-val-range-min="18"
 *   data-val-range-max="120"
 *   data-val-regex="..."             ← [RegularExpression]
 *   data-val-regex-pattern="..."
 *   data-val-equalto="..."           ← [Compare]
 *   data-val-equalto-other="..."
 *   data-val-email="..."             ← [EmailAddress]
 *
 * Span attributes rendered by asp-validation-for:
 *   data-valmsg-for="FieldName"      ← identifies which field's error to display
 *   data-valmsg-replace="true"       ← unobtrusive replaces the span text on error
 *
 * Div attributes rendered by asp-validation-summary:
 *   data-valmsg-summary="true"       ← aggregates all field errors into the div
 */

var builder = WebApplication.CreateBuilder(args); // configure services before Build()

builder.Services.AddControllersWithViews(); // registers MVC controllers + Razor Views

var app = builder.Build();

app.UseStaticFiles(); // serve wwwroot (needed if using LibMan / local script files)
app.UseRouting();     // enable endpoint routing (required before MapDefaultControllerRoute)
app.MapDefaultControllerRoute(); // route: {controller=Home}/{action=Index}/{id?}

app.Run();

/*
 * QUICK REFERENCE — Client-Side Validation
 *
 * Three script delivery options (choose one per project):
 *   CDN:    <script src="https://cdnjs.cloudflare.com/ajax/libs/...">
 *   LibMan: libman.json → restores to wwwroot/lib; <script src="~/lib/...">
 *   Bundle: bundleconfig.json + BuildBundlerMinifier NuGet pkg; <script src="~/bundles/...">
 *
 * Enabling/disabling unobtrusive validation at page level:
 *   $.validator.setDefaults({ ignore: "" });  // validate hidden fields too
 *   $.validator.unobtrusive.options = { ... };
 *
 * Re-parse after AJAX-injected HTML (dynamic DOM):
 *   $.validator.unobtrusive.parse("#myForm");   // re-read data-val-* for new fields
 *   // or pass a container element:
 *   $.validator.unobtrusive.parse($(".dynamic-section"));
 *
 * Custom validator registration pattern:
 *   jQuery.validator.addMethod("rulename", function(value, element, params) { ... });
 *   $.validator.unobtrusive.adapters.addBool("rulename");       // no extra params
 *   $.validator.unobtrusive.adapters.addSingleVal("rulename", "paramname"); // 1 param
 *   $.validator.unobtrusive.adapters.addMinMax("rulename", "minrule", "maxrule", "min", "max");
 *   $.validator.unobtrusive.adapters.add("rulename", ["p1","p2"], function(opts) { ... });
 *
 * IClientModelValidator interface:
 *   void AddValidation(ClientModelValidationContext context)
 *   context.Attributes — IDictionary<string, string>; add "data-val-*" keys here
 *   MergeAttribute helper: only adds if key is not already present
 *
 * ModelState on the server is always the authority — never skip server validation.
 */
