// Stock Trading https://www.onlinegdb.com/online_java_compiler#

/*<bug-task1>

 * We are developing a stock trading data management software that tracks
 * the prices of different stocks over time and provides useful statistics.
 *
 * The program includes three classes: Stock, PriceRecord, StockCollection.
 *
 * Classes:
 *   Stock           — data about a particular stock (symbol, name)
 *   PriceRecord     — a single price record for a stock (date, price)
 *   StockCollection — manages price records for a particular stock

 * TASK 1: Read the code. The test for StockCollection is not passing
 *         due to a bug. Find and fix the bug.
 </bug-task1>
 */

/*<task2>
 * TASK 2: Add "getBiggestChange" to StockCollection. This function
 *         calculates and returns the largest change in stock price between
 *         any two consecutive days in the price records of a stock, along
 *         with the dates of the change in a list.
 *
 * Example: Price records for a stock:
 *   Price:  110   112    90   105
 *   Date:  2023-06-29  2023-07-01  2023-06-25  2023-07-06
 *
 * Stock price changes (sorted based on date):
 *   Date:  2023-06-25 → 2023-06-29 → 2023-07-01 → 2023-07-06
 *   Price:     90    →    110     →     112     →     105
 *   Change:       +20          +2           -7
 *
 * Biggest change: 20 (from 2023-06-25 to 2023-06-29)
 </task2>
 */

/*<task3>
 * Task 3: The `get_total` function should be used to get the total price of all the stocks owned by
 * the user at the latest date. This functions helps the user to calculate the current value of their portfolio. This function takes the `stock_collections` list as input which contains StockCollections for all stocks.
 * The StockCollections list is guaranteed to contain all stocks which would be present in the Tradebook and the stock collection for each stock is guaranteed to have the price record for all transaction dates.
 </task3>
 */

/*<task4>
 * Task 4:
 *  We want to add a new function called get_profit to the Tradebook class.
 * This function calculates the total net profit or loss generated by the user's portfolio across all stocks. This includes both "Realized Profit" (money made/lost from stocks already sold) and "Unrealized Profit" (the current value of stocks still held compared to what was paid for them).
 *  The logic for calculating profit should be:
 * Total Profit = (Total Revenue from Sells) + (Current Value of Remaining Holdings) - (Total Cost of All Buys)
 </task4>
 **/

using System;
using System.Collections.Generic;
using System.Linq;

namespace DotNetQuestions
{
    class Stock
    {
        public string Symbol;
        public string Name;

        public Stock(string symbol, string name)
        {
            this.Symbol = symbol;
            this.Name = name;
        }

        public override bool Equals(object other)
        {
            if (this == other) return true;
            if (other == null || GetType() != other.GetType()) return false;
            Stock stock = (Stock)other;
            return Symbol.Equals(stock.Symbol) && Name.Equals(stock.Name);
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Symbol, Name);
        }
    }

    class PriceRecord
    {
        public Stock Stock;
        public int Price;
        public string Date;

        public PriceRecord(Stock stock, int price, string date)
        {
            this.Stock = stock;
            this.Price = price;
            this.Date = date;
        }
    }

    class Transaction
    {
        public Stock Stock;
        public string Type; // "buy" or "sell"
        public string Date;
        public int Quantity;

        public Transaction(Stock stock, string type, string date, int quantity)
        {
            this.Stock = stock;
            this.Type = type;
            this.Date = date;
            this.Quantity = quantity;
        }
    }

    class Tradebook
    {
        public List<Transaction> Transactions = new List<Transaction>();

        public void AddTransaction(Transaction t)
        {
            Transactions.Add(t);
        }

        // TASK 3: Logic missing - returns 0
        public int GetTotal(List<StockCollection> stockCollections)
        {
            return 0;
        }

        // TASK 4: Logic missing - returns 0.0
        public double GetProfit(List<StockCollection> stockCollections)
        {
            return 0.0;
        }
    }

    class StockCollection
    {
        public List<PriceRecord> PriceRecords = new List<PriceRecord>();
        public Stock Stock;

        public StockCollection(Stock stock)
        {
            this.Stock = stock;
        }

        public int GetNumPriceRecords()
        {
            return PriceRecords.Count;
        }

        public void AddPriceRecord(PriceRecord priceRecord)
        {
            if (!priceRecord.Stock.Equals(this.Stock))
            {
                throw new ArgumentException("Stock mismatch");
            }
            PriceRecords.Add(priceRecord);
        }

        // TASK 1 BUG: Crashes on empty list
        public int GetMaxPrice()
        {
            return PriceRecords.Select(r => r.Price).Max();
        }

        // TASK 1 BUG: Crashes on empty list
        public int GetMinPrice()
        {
            return PriceRecords.Select(r => r.Price).Min();
        }

        // TASK 1 BUG: Division by zero on empty list
        public double GetAvgPrice()
        {
            double total = PriceRecords.Select(r => r.Price).Sum();
            return total / PriceRecords.Count;
        }

        // TASK 2: Unimplemented
        public object[] GetBiggestChange()
        {
            return null;
        }

        // TASK 2: Unimplemented
        public List<object[]> GetAllChanges()
        {
            return new List<object[]>();
        }
    }

    public class StockTradingMockStub
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("=== RUNNING STOCK TRADING TEST SUITE ===\n");

            // <bug-task1>
            Run("TASK 1: Bug Check (Empty List)", () =>
            {
                Stock s = new Stock("AAPL", "Apple");
                StockCollection sc = new StockCollection(s);
                Assert.AssertEquals(-1, sc.GetMaxPrice());
            });
            // </bug-task1>

            // <task2>
            Run("TASK 2: Biggest Change Logic", () =>
            {
                Stock s = new Stock("AAPL", "Apple");
                StockCollection sc = new StockCollection(s);
                sc.AddPriceRecord(new PriceRecord(s, 90, "2023-06-25"));
                sc.AddPriceRecord(new PriceRecord(s, 110, "2023-06-29"));
                object[] expected = { 20, "2023-06-25", "2023-06-29" };
                Assert.AssertArrayEquals(expected, sc.GetBiggestChange());
            });
            // </task2>

            // <task3>
            Run("TASK 3: Portfolio Valuation", () =>
            {
                Tradebook tb = new Tradebook();
                Stock s = new Stock("AAPL", "Apple");
                StockCollection sc = new StockCollection(s);
                sc.AddPriceRecord(new PriceRecord(s, 105, "2023-07-06"));
                tb.AddTransaction(new Transaction(s, "buy", "2023-06-25", 10));
                Assert.AssertEquals(1050, tb.GetTotal(new List<StockCollection> { sc }));
            });
            // </task3>

            // <task4>
            Run("TASK 4: Profit Calculation", () =>
            {
                Tradebook tb = new Tradebook();
                Stock s = new Stock("AAPL", "Apple");
                StockCollection sc = new StockCollection(s);
                sc.AddPriceRecord(new PriceRecord(s, 100, "2023-01-01"));
                sc.AddPriceRecord(new PriceRecord(s, 150, "2023-01-02"));
                tb.AddTransaction(new Transaction(s, "buy", "2023-01-01", 10));
                Assert.AssertEquals(500.0, tb.GetProfit(new List<StockCollection> { sc }), 0.1);
            });
            // </task4>
        }

        static void Run(string name, Action test)
        {
            try
            {
                test();
                Console.WriteLine("PASS: " + name);
            }
            catch (Exception e)
            {
                Console.WriteLine("FAIL: " + name);
                Console.WriteLine("      Message: " + (e.Message != null ? e.Message : e.ToString()));
                Console.WriteLine("-------------------------------------------");
            }
        }
    }

    class Assert
    {
        public static void AssertEquals(int expected, int actual)
        {
            if (expected != actual) throw new Exception("Mismatch! Expected: " + expected + ", Got: " + actual);
        }

        public static void AssertEquals(double expected, double actual, double delta)
        {
            if (Math.Abs(expected - actual) > delta) throw new Exception("Mismatch! Expected: " + expected + ", Got: " + actual);
        }

        public static void AssertArrayEquals(object[] expected, object[] actual)
        {
            if (actual == null) throw new Exception("Mismatch! Expected an array but got: NULL");
            if (!expected.SequenceEqual(actual))
            {
                throw new Exception("Mismatch! Expected: " + ArrayToString(expected) + ", Got: " + ArrayToString(actual));
            }
        }

        private static string ArrayToString(object[] arr)
        {
            return "[" + string.Join(", ", arr) + "]";
        }
    }
}
