using System;
using CodeFirstModelsAndMigrations.Utils;

namespace CodeFirstModelsAndMigrations;

/*
 * =============================================================================
 * TOPIC: Code-First Models and Migrations - define entity classes in C#, let EF Core
 *        infer schema through conventions, version DDL with migrations, and apply
 *        changes to SQL Server with Update-Database or Database.Migrate().
 *
 * WHY IT MATTERS:
 *   Greenfield .NET apps usually start Code-First: the team evolves C# models and
 *   checks migration files into source control. Each environment replays the same
 *   Up() scripts so dev, test, and production stay aligned. Understanding
 *   conventions, snapshots, and __EFMigrationsHistory prevents "works on my machine"
 *   schema drift.
 *
 * WHAT YOU WILL LEARN:
 *   1.  Code-First entity classes (POCOs mapped to tables)
 *   2.  EF Core conventions by default (keys, names, FKs, types)
 *   3.  DbContext and DbSet<T> exposing the model
 *   4.  LocalDB connection string for EfCoreTutorial
 *   5.  dotnet ef migrations add / Add-Migration
 *   6.  dotnet ef database update / Update-Database
 *   7.  Migration Up/Down methods and Designer metadata
 *   8.  Model snapshot (StoreDbContextModelSnapshot.cs)
 *   9.  __EFMigrationsHistory and Database.Migrate()
 *
 * CHAPTER MAP:
 *   1.  Code-First entity classes           -> Models/Category.cs, Models/Product.cs
 *   2.  EF Core conventions by default      -> Models/Category.cs, Models/Product.cs
 *   3.  DbContext and DbSet<T>              -> Data/StoreDbContext.cs
 *   4.  LocalDB connection string           -> Utils/ConnectionHelper.cs
 *   5.  dotnet ef migrations add            -> Utils/MigrationCliReference.cs, Data/StoreDbContextFactory.cs, Migrations/
 *   6.  dotnet ef database update           -> Utils/MigrationCliReference.cs
 *   7.  Database.Migrate() demo             -> Utils/MigrationDemo.cs
 *   8.  __EFMigrationsHistory               -> Utils/MigrationDemo.cs
 *   9.  EnsureCreated vs Migrate            -> Utils/MigrationCliReference.cs
 *  10.  Demonstration                       -> Program.cs Main (below)
 *
 * DATABASE: EfCoreTutorial on (localdb)\MSSQLLocalDB
 *   Server=(localdb)\MSSQLLocalDB;Database=EfCoreTutorial;Integrated Security=true;TrustServerCertificate=true
 *
 * Migrations/ contains InitialCreate generated by:
 *   dotnet ef migrations add InitialCreate
 * Main calls Database.Migrate() to apply them at runtime (same effect as Update-Database).
 * =============================================================================
 */
public class Program
{
    /*
     * SECTION 10: DEMONSTRATION - Main orchestrates the chapter demo
     */
    public static void Main(string[] args)
    {
        Console.WriteLine("=== 03. Code-First Models & Migrations ===");
        Console.WriteLine();

        MigrationCliReference.ExplainAddMigration();
        Console.WriteLine();
        MigrationCliReference.ExplainDatabaseUpdate();
        Console.WriteLine();
        MigrationCliReference.ExplainEnsureCreatedVsMigrate();
        Console.WriteLine();

        Console.WriteLine("--- SECTION 7: Database.Migrate() ---");
        bool schemaReady = MigrationDemo.TryApplyMigrations(out string? failure);
        if (!schemaReady)
        {
            Console.WriteLine("Database demo skipped - LocalDB unavailable or migration error.");
            Console.WriteLine($"  {failure}");
            Console.WriteLine("  Install SQL Server Express LocalDB: Server=(localdb)\\MSSQLLocalDB");
            Console.WriteLine("  Open Migrations/ to read InitialCreate Up() and ModelSnapshot.");
            return;
        }

        if (failure is not null)
        {
            Console.WriteLine($"  Note: {failure}");
            Console.WriteLine("  Continuing with existing tables for read/seed demo.");
        }
        else
        {
            Console.WriteLine("  Migrate() applied pending migrations to EfCoreTutorial.");
        }
        Console.WriteLine();

        MigrationDemo.SeedSampleDataIfEmpty();
        Console.WriteLine("--- Products after Code-First schema (convention-mapped) ---");
        foreach (var product in MigrationDemo.ReadAllProducts())
        {
            Console.WriteLine($"  {product}");
        }
        Console.WriteLine();

        Console.WriteLine("--- SECTION 8: __EFMigrationsHistory ---");
        foreach (var row in MigrationDemo.ReadMigrationHistory())
        {
            Console.WriteLine($"  {row.MigrationId}  (EF {row.ProductVersion})");
        }
        Console.WriteLine();
        Console.WriteLine("  Open Migrations/*_InitialCreate.cs for Up()/Down() DDL.");
        Console.WriteLine("  Open Migrations/StoreDbContextModelSnapshot.cs for the frozen model.");
    }
}

/*
 * =========================================================================
 * QUICK REFERENCE - CODE-FIRST MODELS & MIGRATIONS
 * =========================================================================
 *
 * --- Entity (Code-First) ---
 *
 *   public class Product
 *   {
 *       public int ProductId { get; set; }   // PK by convention
 *       public string Name { get; set; } = string.Empty;
 *       public int CategoryId { get; set; }  // FK by convention
 *       public Category Category { get; set; } = null!;
 *   }
 *
 * --- DbContext ---
 *
 *   public class StoreDbContext : DbContext
 *   {
 *       public StoreDbContext(DbContextOptions<StoreDbContext> options) : base(options) { }
 *       public DbSet<Product> Products => Set<Product>();
 *   }
 *
 * --- CLI workflow ---
 *
 *   dotnet tool install --global dotnet-ef
 *   dotnet ef migrations add InitialCreate
 *   dotnet ef database update
 *   dotnet ef migrations remove        # undo last unapplied migration
 *   dotnet ef migrations script        # generate SQL file for DBAs
 *
 * --- PMC (Visual Studio) ---
 *
 *   Add-Migration InitialCreate
 *   Update-Database
 *   Update-Database -Migration 0       # revert all
 *
 * --- Runtime apply ---
 *
 *   context.Database.Migrate();         // pending migrations only
 *   context.Database.EnsureCreated();  // no migration history - avoid in real apps
 *
 * --- Key files ---
 *
 *   Migrations/{timestamp}_Name.cs           Up()/Down()
 *   Migrations/{timestamp}_Name.Designer.cs  build metadata
 *   Migrations/*ModelSnapshot.cs             current model fingerprint
 *   dbo.__EFMigrationsHistory                applied migration IDs
 *
 * --- Forward references ---
 *
 *   ch02 DbContext & DbSet           options, DI, lifetime (preview in Data/StoreDbContext.cs)
 *   ch06 Relationships               cardinality, cascade, many-to-many
 *   ch07 Fluent API & Annotations    override conventions
 *   ch05 CRUD & SaveChanges          Add/Update/Remove after schema exists
 *
 * --- Common mistakes ---
 *
 *  Mistake                              | Result
 *  -------------------------------------|----------------------------------
 *  Model change without new migration   | Runtime errors / column mismatch
 *  EnsureCreated then migrations        | Conflicting schema paths
 *  Edit applied migration Up() by hand  | History out of sync - add new migration instead
 *  Delete DB but keep old connection    | Migrate() recreates from scratch (OK)
 *  Missing Design package               | dotnet ef fails at design time
 *
 * =========================================================================
 */
