/*
 * FILE ROLE: ProductViewModel — the view model used by ProductsController for the
 *   Products CRUD demo.  Carries Data Annotations that drive both server-side
 *   ModelState validation (used by ValidateModelActionFilter) and client-side
 *   unobtrusive validation generated by Tag Helpers in Create.cshtml.
 *
 * SECTIONS IN THIS FILE:
 *   SECTION 11 — ProductViewModel: Data Annotations for server-side ModelState,
 *                GetSamples() helper for in-memory demo data
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ActionFiltersMvc.Models;

/*
 * SECTION 11: ProductViewModel — STRONGLY-TYPED VIEW MODEL WITH DATA ANNOTATIONS
 * ─────────────────────────────────────────────────────────────────────────────
 * Data Annotations from System.ComponentModel.DataAnnotations drive validation at
 * two layers:
 *
 *   Server-side: ASP.NET Core model binding runs annotation validators during binding.
 *     Errors are added to ModelState.  ValidateModelActionFilter (see Filters/) reads
 *     ModelState.IsValid and short-circuits with a ViewResult before the action runs.
 *
 *   Client-side: The asp-validation-for and asp-validation-summary tag helpers in
 *     Create.cshtml emit data-* attributes that jQuery Unobtrusive Validation reads,
 *     giving immediate feedback without a server round-trip.
 *
 * COMMON DATA ANNOTATION ATTRIBUTES:
 *   [Required]                  → field must be non-null / non-empty string
 *   [StringLength(max, Min=n)]  → string length bounds
 *   [Range(min, max)]           → numeric range (works with decimal, int, double)
 *   [Display(Name = "...")]     → label text for <label asp-for="..."> tag helper
 *   [DataType(DataType.Currency)] → hint for display formatting (no validation)
 *
 * NULLABILITY:
 *   Non-nullable reference properties (Name) are implicitly [Required] in .NET 6+
 *   because model binding cannot produce a non-null value from a missing form field
 *   without an explicit [Required] — keep [Required] explicit for clarity.
 *   Nullable properties (Description?) are optional by convention.
 */
public sealed class ProductViewModel
{
    // Id is not validated — only used for display in the Index view (populated from GetSamples)
    public int Id { get; set; }

    [Required(ErrorMessage = "Product name is required.")]
    [StringLength(100, MinimumLength = 2, ErrorMessage = "Name must be between 2 and 100 characters.")]
    [Display(Name = "Product Name")]
    public string Name { get; set; } = string.Empty;

    [Range(0.01, 99999.99, ErrorMessage = "Price must be between $0.01 and $99,999.99.")]
    [Display(Name = "Unit Price")]
    public decimal Price { get; set; }

    [StringLength(500, ErrorMessage = "Description cannot exceed 500 characters.")]
    [Display(Name = "Description")]
    public string? Description { get; set; } // optional — nullable

    // ── In-memory sample data for the demo ──────────────────────────────────
    // In a real app this would come from a repository / service layer.
    public static IEnumerable<ProductViewModel> GetSamples() =>
        new[]
        {
            new ProductViewModel { Id = 1, Name = "Widget A",   Price = 9.99m,  Description = "A basic widget." },
            new ProductViewModel { Id = 2, Name = "Widget B",   Price = 19.99m, Description = "An improved widget." },
            new ProductViewModel { Id = 3, Name = "Widget Pro", Price = 49.99m, Description = "The professional widget." }
        };
}
